spring:
  application:
    name: aereopuerto

  # MySQL config
  datasource:
    url: jdbc:mysql://localhost:3306/pf_prog3_gestorAeropuerto
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  # JPA
  jpa:
    hibernate:
      ddl-auto: update #crea/actualiza tablas auto
    show-sql: true # habilitado para testeo y ver las consultas en consola, despues lo podemos desactivar
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  # config redis
  #data:
  # redis:
   #  host: localhost
    # port: 6379

  # configuracion del cache, es opcional pero para tenerlo en cuenta por si lo queremos configurar de forma global
  #cache:
   # type: redis
